name: Integration Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Build
      run: docker-compose build
      working-directory: ./integrationTests
    - name: Test
      run: docker-compose run test
      working-directory: ./integrationTests
