name: Integration Tests

on: [pull_request]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Go to integration tests folder
      run: cd integrationTests
    - name: Build
      run: docker-compose build
    - name: Test
      run: docker-compose run test
